# Generated by Django 5.2.17 on 2026-08-26 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="general", max_length=50)),
                ("question_en", models.CharField(max_length=300)),
                ("question_bn", models.CharField(blank=True, max_length=300)),
                ("answer_en", models.TextField()),
                ("answer_bn", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ item",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=120)),
                ("name_bn", models.CharField(blank=True, max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name, e.g. 'wrench'.",
                        max_length=50,
                    ),
                ),
                ("summary_en", models.CharField(max_length=300)),
                ("summary_bn", models.CharField(blank=True, max_length=300)),
                ("body_en", models.TextField(blank=True)),
                ("body_bn", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="services/")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Acme Services", max_length=120),
                ),
                ("tagline_en", models.CharField(blank=True, max_length=200)),
                ("tagline_bn", models.CharField(blank=True, max_length=200)),
                ("phone_primary", models.CharField(blank=True, max_length=30)),
                ("phone_secondary", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("address_en", models.TextField(blank=True)),
                ("address_bn", models.TextField(blank=True)),
                ("hours_en", models.CharField(blank=True, max_length=200)),
                ("hours_bn", models.CharField(blank=True, max_length=200)),
                ("google_maps_embed_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("meta_title_en", models.CharField(blank=True, max_length=160)),
                ("meta_title_bn", models.CharField(blank=True, max_length=160)),
                ("meta_description_en", models.CharField(blank=True, max_length=320)),
                ("meta_description_bn", models.CharField(blank=True, max_length=320)),
                ("meta_pixel_id", models.CharField(blank=True, max_length=50)),
                ("ga4_measurement_id", models.CharField(blank=True, max_length=50)),
                ("gtm_container_id", models.CharField(blank=True, max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role_en", models.CharField(max_length=100)),
                ("role_bn", models.CharField(blank=True, max_length=100)),
                ("bio_en", models.TextField(blank=True)),
                ("bio_bn", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("body_en", models.TextField()),
                ("body_bn", models.TextField(blank=True)),
                ("source", models.CharField(default="google", max_length=50)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
