# Generated by Django 5.2.17 on 2026-08-26 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=50, unique=True)),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text='Hex color, e.g. "#22C55E".',
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_terminal", models.BooleanField(default=False)),
                ("counts_as_converted", models.BooleanField(default=False)),
                ("requires_reason", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("phone_normalized", models.CharField(db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("message", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("attribution", models.JSONField(blank=True, default=dict)),
                ("consent_marketing", models.BooleanField(default=False)),
                ("lang", models.CharField(default="en", max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="content.service",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="leads.pipelinestage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("call", "Call"),
                            ("whatsapp_click", "WhatsApp click"),
                            ("email_sent", "Email sent"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "actor",
                    models.CharField(help_text='Username or "system".', max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lead activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.CharField(help_text='Username or "system".', max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="leads.pipelinestage",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="leads.lead",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leads.pipelinestage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
